# Generated by Django 3.2.5 on 2021-08-16 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_bills',
            name='bill_type',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='projectname',
            name='above_below',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
