# Generated by Django 3.2.5 on 2021-08-18 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_auto_20210816_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectexpenses',
            name='expense_receipt',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
