# Generated by Django 3.2.5 on 2021-08-19 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_projectexpenses_expense_receipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectexpenses',
            name='expense_amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='projectexpenses',
            name='expense_receipt',
            field=models.ImageField(blank=True, null=True, upload_to='expense_receipts/'),
        ),
    ]
