# Generated by Django 3.2.5 on 2021-08-19 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_auto_20210819_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectexpenses',
            name='expense_receipt',
            field=models.URLField(),
        ),
    ]
