# Generated by Django 3.2.5 on 2021-08-20 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_alter_projectexpenses_expense_receipt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectname',
            name='amount',
        ),
        migrations.AddField(
            model_name='paidby',
            name='cnic',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paidby',
            name='salary',
            field=models.IntegerField(default=12231),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projectexpenses',
            name='expense_receipt',
            field=models.ImageField(blank=True, null=True, upload_to='expense_receipts/'),
        ),
        migrations.AlterField(
            model_name='projectname',
            name='budget_allocated',
            field=models.DecimalField(decimal_places=2, max_digits=14, null=True),
        ),
    ]
